#!/bin/bash

CONFIG_FILE=$SNAP_DATA/.config

function get_app_to_run()
{
    # Use a default in case config file doesn't exist
    local app=photoviewer
    if [ -e ${config_file} ]; then
        app=$(grep app ${CONFIG_FILE} | cut -d'=' -f2)
    fi

    echo ${app}
}

if [ "$SNAP_ARCH" == "amd64" ]; then
    ARCH="x86_64-linux-gnu"
elif [ "$SNAP_ARCH" == "armhf" ]; then
    ARCH="arm-linux-gnueabihf"
elif [ "$SNAP_ARCH" == "arm64" ]; then
    ARCH="aarch64-linux-gnu"
else
    ARCH="$SNAP_ARCH-linux-gnu"
fi

export LD_LIBRARY_PATH=$SNAP/usr/lib/$ARCH:$LD_LIBRARY_PATH
# Mir config
export MIR_SOCKET=/run/mir_socket
export MIR_CLIENT_PLATFORM_PATH=$SNAP/mir-libs/$ARCH/mir/client-platform
export LD_LIBRARY_PATH="$SNAP/mir-libs/$ARCH:$LD_LIBRARY_PATH"
# Mesa Libs
export LD_LIBRARY_PATH=$SNAP/mir-libs/$ARCH/mesa:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$SNAP/mir-libs/$ARCH/mesa-egl:$LD_LIBRARY_PATH

# XKB config
export XKB_CONFIG_ROOT=$SNAP/usr/share/X11/xkb

# Qt Platform to Mir
export QT_QPA_PLATFORM=ubuntumirclient
export QTCHOOSER_NO_GLOBAL_DIR=1
export QT_SELECT=snappy-qt5
# Qt Libs
export LD_LIBRARY_PATH=$SNAP/usr/lib/$ARCH/qt5/libs:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$SNAP/usr/lib/$ARCH/pulseaudio:$LD_LIBRARY_PATH
# Qt Modules
export QT_PLUGIN_PATH=$SNAP/usr/lib/$ARCH/qt5/plugins
export QML2_IMPORT_PATH=$SNAP/usr/lib/$ARCH/qt5/qml
# XDG Config
export XDG_CONFIG_DIRS=$SNAP/etc/xdg:$XDG_CONFIG_DIRS
export XDG_CONFIG_DIRS=$SNAP/usr/xdg:$XDG_CONFIG_DIRS
export XDG_DATA_DIRS=$SNAP/usr/share:$XDG_DATA_DIRS
# needed for fontconfig
export XDG_DATA_HOME=$SNAP/usr/share
export FONTCONFIG_PATH=$SNAP/etc/fonts/config.d
export FONTCONFIG_FILE=$SNAP/etc/fonts/fonts.conf

export ARCH

while true; do

    app_to_run=$(get_app_to_run)

    $SNAP/apps/${app_to_run} &
    app_pid=$!

    # Config file should exist but let's make sure
    # otherwise, inotifywait will exit immediately and loop will
    # keep restarting server
    if [ -e "${CONFIG_FILE}" ]; then
        $SNAP/usr/bin/inotifywait -e modify ${CONFIG_FILE} &
        inotify_pid=$!
    fi

    # Wait for a notification or app death
    wait -n

    # app may have died, stop waiting for config notifications
    if [ -n "${inotify_pid}" ]; then
        kill ${inotify_pid} > /dev/null
        wait ${inotify_pid}
        unset inotify_pid
    fi

    echo "Shutting down ${app_to_run} (pid: ${app_pid})"
    kill ${app_pid} > /dev/null
    if [ $? -ne 0 ]; then
        echo "${app_to_run} was already dead!"
        exit 1
    fi

    # Ensure app processes has quit for sure
    wait ${app_pid}
    unset app_pid
done
