name: mir-client
version: 0.19
summary: Example app on Mir stack
description: "This example can be used as a guide by other mir client snaps to render guis"
icon: mir.png
# as this is an example, type could be changed to oem
type: app

apps:
  client-start:
    command: bin/client-start
    daemon: simple
    uses:
      - migration-stuff
#    security-template: unconfined
uses:
  migration-stuff:
    type: migration-skill
    security-template: unconfined
parts:
  mir-client:
    plugin: mir-client
  qmldemo:
    plugin: copy
    files:
      demo.qml: demo.qml
#    all stage-packages taken care of by plugin
#  samegame:
#    plugin: copy
#    files:
#      samegame: samegame
  clocks:
    plugin: copy
    files:
      clocks: clocks
  glue:
    plugin: copy
    files:
      client-start: bin/client-start
