name: mir-client
version: 0.24
summary: Example app on Mir stack
description: "This example can be used as a guide by other mir client snaps to render guis"
# as this is an example, type could be changed to oem
confinement: strict
type: app

apps:
  client-start:
    command: bin/client-start
    daemon: simple
    plugs:
      - mir
      - opengl
parts:
  examples:
    plugin: nil
    stage-packages:
      - qtdeclarative5-dev
      - qtdeclarative5-examples
      - qmlscene
      - qtdeclarative5-qtmir-plugin
      - mir-graphics-drivers-desktop
      - mir-demos
      - qtubuntu-desktop
      - ttf-ubuntu-font-family
      - qml-module-qt-labs-folderlistmodel
      - qml-module-qt-labs-settings
      - qml-module-qt-websockets
      - qml-module-qtfeedback
      - qml-module-qtgraphicaleffects
      - qml-module-qtlocation
      - qml-module-qtmultimedia
      - qml-module-qtorganizer
      - qml-module-qtpositioning
      - qml-module-qtqml-models2
      - qml-module-qtqml-statemachine
      - qml-module-qtquick-controls
      - qml-module-qtquick-dialogs
      - qml-module-qtquick-layouts
      - qml-module-qtquick-localstorage
      - qml-module-qtquick-particles2
      - qml-module-qtquick-privatewidgets
      - qml-module-qtquick-window2
      - qml-module-qtquick-xmllistmodel
      - qml-module-qtquick2
      - qml-module-qtsensors
      - qml-module-qtsysteminfo
      - qml-module-qttest
      - qml-module-qtwebkit
      - intltool
      - qtdeclarative5-dev
# alternate clients to play with
  photoviewer:
    after:
      - examples
    qt-version: qt5
    plugin: qmake
    source: https://github.com/qt/qtdeclarative.git
    project-files:
      - examples/quick/demos/photoviewer/photoviewer.pro
    build-packages:
      - build-essential
      - qtquick1-5-dev
  qmldemo:
    plugin: copy
    files:
      demo.qml: demo.qml
  environment:
    plugin: copy
    files:
      snappy-qt5.conf: etc/xdg/qtchooser/snappy-qt5.conf
  glue:
    plugin: copy
    files:
      client-start: bin/client-start
