name: mir-client
version: 0.24.1
summary: Example app on Mir stack
description: "This example can be used as a guide by other mir client snaps to render guis"
confinement: strict
grade: devel

apps:
  client-start:
    command: bin/client-start
    daemon: simple
    plugs:
      - mir
      - opengl
parts:
  qt-support:
    plugin: nil
    stage-packages:
      - qtdeclarative5-dev
      - qtdeclarative5-examples
      - qmlscene
      - qtdeclarative5-qtmir-plugin
      - qtubuntu-desktop
      - ttf-ubuntu-font-family
      - qml-module-qt-labs-folderlistmodel
      - qml-module-qt-labs-settings
      - qml-module-qt-websockets
      - qml-module-qtfeedback
      - qml-module-qtgraphicaleffects
      - qml-module-qtlocation
      - qml-module-qtmultimedia
      - qml-module-qtorganizer
      - qml-module-qtpositioning
      - qml-module-qtqml-models2
      - qml-module-qtqml-statemachine
      - qml-module-qtquick-controls
      - qml-module-qtquick-dialogs
      - qml-module-qtquick-layouts
      - qml-module-qtquick-localstorage
      - qml-module-qtquick-particles2
      - qml-module-qtquick-privatewidgets
      - qml-module-qtquick-window2
      - qml-module-qtquick-xmllistmodel
      - qml-module-qtquick2
      - qml-module-qtsensors
      - qml-module-qtsysteminfo
      - qml-module-qttest
      - qml-module-qtwebkit
      - intltool

  mir-demos:
    plugin: nil
    stage-packages:
      - mir-graphics-drivers-desktop
      - mir-demos

  photoviewer:
    after: [qt-support]
    qt-version: qt5
    plugin: qmake
    source: https://github.com/qt/qtdeclarative.git
    project-files:
      - examples/quick/demos/photoviewer/photoviewer.pro
    build-packages:
      - build-essential
      - qtdeclarative5-dev
      - qtquick1-5-dev
      - libqt5xmlpatterns5-dev

  qmldemo:
    plugin: dump
    source: .
    snap: [demo.qml]

  environment:
    plugin: dump
    source: .
    organize:
      snappy-qt5.conf: etc/xdg/qtchooser/snappy-qt5.conf

  glue:
    plugin: dump
    source: .
    organize:
      client-start: bin/client-start
