name: mir-client
version: 0.24.1
summary: Example app on Mir stack
description: This example can be used as a guide by other mir client snaps to render guis
confinement: strict
grade: devel

apps:
  client-start:
    command: bin/client-start
    daemon: simple
    plugs:
      - mir
      - opengl

plugs:
  mir-libs:
    interface: content
    target: mir-libs
    default-provider: mir-libs:mir-libs

parts:
  qtubuntu:
    plugin: nil
    stage-packages:
      - qtubuntu-desktop

  qt-examples:
    plugin: nil
    stage-packages:
      - qtdeclarative5-examples
      - qml-module-qtquick-window2 #qtdeclarative5-examples is missing this dep, which is used by various examples

  mir-demos:
    plugin: nil
    stage-packages:
      - mir-demos

  photoviewer:
    qt-version: qt5
    plugin: qmake
    source: https://github.com/qt/qtdeclarative.git
    project-files:
      - examples/quick/demos/photoviewer/photoviewer.pro
    build-packages:
      - build-essential
      - qtdeclarative5-dev
      - qtquick1-5-dev
      - libqt5xmlpatterns5-dev
    stage-packages:
      - qml-module-qtquick-controls
      - qml-module-qtqml-models2

  qmldemo:
    plugin: dump
    source: .
    snap: [demo.qml]

  environment:
    plugin: dump
    source: .
    organize:
      snappy-qt5.conf: etc/xdg/qtchooser/snappy-qt5.conf

  glue:
    plugin: dump
    source: .
    organize:
      client-start: bin/client-start
      configure: meta/hooks/configure #FIXME: use actual hooks attribute when snapcraft supports it

  mir-libs-target:
    plugin: dump
    source: .
    snap: [mir-libs]
