name: mir-kiosk-apps
version: 0.3.0
summary: Example apps to run with mir-kiosk
description: Example apps to run with mir-kiosk
confinement: strict
grade: devel
base: core18

apps:
  daemon:
    command: run-daemon wayland-launch "$SNAP/apps/$(snapctl get app)"
    daemon: simple
    restart-condition: on-failure

  mir-kiosk-apps:
    command: wayland-launch "$SNAP/apps/$(snapctl get app)"

plugs:
  network:
  opengl:
  wayland:

environment:
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
  # XKB config
  XKB_CONFIG_ROOT: ${SNAP}/usr/share/X11/xkb
  # Qt Platform to Wayland
  QT_QPA_PLATFORM: wayland
  QT_QPA_PLATFORM_PLUGIN_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5/plugins/platforms/
  QTCHOOSER_NO_GLOBAL_DIR: 1
  QT_SELECT: snappy-qt5
  # Qt Modules
  QT_PLUGIN_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5/plugins
  QML2_IMPORT_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/qt5/qml
  # XDG Config
  XDG_CONFIG_DIRS: ${SNAP}/etc/xdg:$XDG_CONFIG_DIRS
  XDG_DATA_DIRS: ${SNAP}/usr/share:$XDG_DATA_DIRS
  # Needed for fontconfig
  XDG_DATA_HOME: ${SNAP}/usr/share
  FONTCONFIG_PATH: ${SNAP}/etc/fonts/conf.d
  FONTCONFIG_FILE: ${SNAP}/etc/fonts/fonts.conf
  # GL Config
  LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri

parts:
  qtwayland:
    plugin: nil
    stage-packages:
      - qtwayland5

  qt-examples:
    plugin: nil
    stage-packages:
      - qtdeclarative5-examples
      - qml-module-qtquick-window2 #qtdeclarative5-examples is missing this dep, which is used by various examples
      - qml-module-qt-labs-folderlistmodel #Another missing dep, needed by photosurface
      - qml-module-qtquick-controls #Missing dep, needed by photoviewer
    organize:
      usr/lib/*/qt5/examples/quick/demos: qt-demos

  qmldemo:
    plugin: dump
    source: qmldemo
    stage-packages: [qmlscene]
    organize:
      spinning-rect.qml: qml/spinning-rect.qml
      usr/lib/qt5/bin/qmlscene: bin/qmlscene
    prime:
     - qml
     - bin/qmlscene
     - usr/lib/libQt*

  qtchooser-config:
    plugin: dump
    source: qtconfig
    organize:
      snappy-qt5.conf: etc/xdg/qtchooser/snappy-qt5.conf

  glue:
    plugin: dump
    source: glue

  mir-kiosk-snap-launch:
    plugin: dump
    source: https://github.com/MirServer/mir-kiosk-snap-launch.git
    override-build: |
      echo "snapctl set app=rssnews" >> $SNAPCRAFT_PART_BUILD/meta/hooks/install
      echo "[ -e \"\$SNAP/apps/\$(snapctl get app)\" ] || snapctl set app=rssnews" >> $SNAPCRAFT_PART_BUILD/meta/hooks/post-refresh
      $SNAPCRAFT_PART_BUILD/build-with-plugs.sh network opengl wayland

  app-wrappers:
    plugin: dump
    source: app-wrappers
    prime: [apps]

  inotify-tools:
    plugin: nil
    stage-packages: [inotify-tools]
    prime:
     - usr/bin/inotifywait
     - usr/lib
