name: mir-kiosk-apps
version: 0.1
summary: Example apps to run with mir-kiosk
description: Example apps to run with mir-kiosk
confinement: strict
grade: devel

apps:
  mir-kiosk-app-daemon:
    command: bin/mir-kiosk-app-daemon
    daemon: simple
    plugs:
      - mir
      - opengl
      - network
      - mir-libs

plugs:
  mir-libs:
    interface: content
    content: mir0
    target: mir-libs
    default-provider: mir-libs:mir-libs

parts:
  qtubuntu:
    plugin: nil
    stage-packages:
      - qtubuntu-desktop
      - xdg-user-dirs
    build-attributes:
     - no-system-libraries
    prime:
     - -usr/lib/*/libmir* #Use the libraries from mir-libs content plug
     - usr/lib/*/lib*.so*
     - usr/lib/*/qt5
     - etc/xdg

  qt-examples:
    plugin: nil
    stage-packages:
      - qtdeclarative5-examples
      - qml-module-qtquick-window2 #qtdeclarative5-examples is missing this dep, which is used by various examples
      - qml-module-qt-labs-folderlistmodel #Another missing dep, needed by photosurface
      - qml-module-qtquick-controls #Missing dep, needed by photoviewer
    build-attributes:
     - no-system-libraries
    organize:
      usr/lib/*/qt5/examples/quick/demos: qt-demos
    prime:
     - qt-demos/*/content
     - qt-demos/*/*.qml
     - -qt-demos/calqlatr # Doesn't work well
     - -qt-demos/photosurface #Crashes
     - -qt-demos/maroon
     - -qt-demos/photoviewer # Not built in Qt 5.5
     - qt-demos/clocks/clocks
     - qt-demos/rssnews/rssnews
     - qt-demos/samegame/samegame
     - qt-demos/stocqt/stocqt
     - qt-demos/tweetsearch/tweetsearch
     - usr/lib
     - usr/share/X11/xkb
     - usr/share/fonts
     - etc/fonts

  mir-demos:
    plugin: nil
    stage-packages:
      - mir-demos
    build-attributes:
     - no-system-libraries
    organize:
      usr/bin: bin
    prime:
     - bin/mir_demo_client_animated_cursor
     - bin/mir_demo_client_cursors
     - bin/mir_demo_client_eglplasma
     - bin/mir_demo_client_egltriangle
     - bin/mir_demo_client_fingerpaint
     - bin/mir_demo_client_progressbar

  photoviewer:
    qt-version: qt5
    plugin: qmake
    source: https://github.com/qt/qtdeclarative.git
    project-files:
      - examples/quick/demos/photoviewer/photoviewer.pro
    build-packages:
      - build-essential
      - qtdeclarative5-dev
      - libqt5xmlpatterns5-dev
    stage-packages:
      - qml-module-qtquick-controls
      - qml-module-qtqml-models2

  qmldemo:
    plugin: dump
    source: qmldemo
    stage-packages: [qmlscene]
    organize:
      spinning-rect.qml: qml/spinning-rect.qml
      usr/lib/*/qt5/bin/qmlscene: bin/qmlscene
    prime:
     - qml
     - bin/qmlscene
     - usr/lib/libQt*

  qtchooser-config:
    plugin: dump
    source: qtconfig
    organize:
      snappy-qt5.conf: etc/xdg/qtchooser/snappy-qt5.conf

  glue:
    plugin: dump
    source: glue

  app-wrappers:
    plugin: dump
    source: app-wrappers
    prime: [apps]

  inotify-tools:
    plugin: nil
    stage-packages: [inotify-tools]
    prime:
     - usr/bin/inotifywait
     - usr/lib

