#!/bin/sh
set -x

app=$(snapctl get app)

if [ -z "${app}" ] || [ ! -e "$SNAP/apps/${app}" ]; then
    snapctl set app=rssnews
fi

if [ "$(snapctl get daemon)" = "" ]
then
  if grep -q snap_core= /proc/cmdline
  then snapctl set daemon=true
  else snapctl set daemon=false
  fi
fi
